site_name: Loubna EL BACHARI
site_description: >-
  Loubna EL BACHARI is the personal website of Loubna EL BACHARI where she shares the projects she is working on.
docs_dir: web/

# Configuration
theme:
    font: false
    name: material
    logo: 'logo.png'
    favicon: 'logo.png'
    palette:
      - scheme: default
        primary: pink
        media: "(prefers-color-scheme: light)"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        accent: 'light blue'
      - scheme: slate
        media: "(prefers-color-scheme: dark)"
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: black
        accent: 'light blue'

    features:
        - navigation.instant
        - content.action.edit
        - content.code.copy
        - content.code.select
        # - announce.dismiss
        - content.code.annotate
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.indexes
        # - navigation.instant
        # - navigation.prune
        #- navigation.sections
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - navigation.expand
        - navigation.footer
        # - toc.integrate
        - navigation.path
        - navigation.indexes
        - content.code.select

    custom_dir: overrides

extra_css:
    - 'stylesheets/extra.css'
    - 'stylesheets/fonts.css'
    - 'stylesheets/home/extra.css'
    - 'stylesheets/home/about.css'

# Customization
extra:
  analytics:
    provider: google
    property: G-4GPL6MXYQ3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our Comments section below.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abdellatif-belmady
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abdellatif-belmady-ab999a133/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/abdellatif.belmady
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@otherways8368/featured
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/abdellatifbelmady/
    # - icon: fontawesome/brands/x-twitter
    #   link: https://twitter.com/AbdellatifBELM

# Repository
repo_url: https://github.com/abdellatif-belmady/Loubna_Portfolio
edit_uri: edit/source/web/

# Copyright
copyright: Copyright &copy; 2023 Loubna EL BACHARI


# Extensions
markdown_extensions:
    - meta
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    # - pymdownx.emoji:
    #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - index.md
